### ISSUE TITLE
Shortcodes used, filter gone

### ISSUE THREAD

**Issue by akzeitlos** [awsmin/wp-job-openings#14]
Hello, short question for shortcodes. If I use the following shortcode, the filter area is not shown. Only search is enabled. Is it possible to enable also the other filter categories?

[awsmjobs specs="job-type:9 10"]

Would be great to hear from you!
Best regards
Andreas

**Comment by anantajitjg** [comment]
Sorry! Currently, this is not possible. When the 'specs' attribute is added in the shortcode, filters will be disabled. We are working on enabling other filters when a particular filter is selected. So, this will be available in any one of the future versions of WP Job Openings Pro.

**Comment by akzeitlos** [comment]
Thats great, thanks!

**Comment by anantajitjg** [comment]
Partial Support for Job Filters in Shortcode when 'specs' attribute is added (Settings > Shortcodes > General > Filtered list of jobs) is supported from WP Job Openings Pro Version 2.1.0.
