### ISSUE TITLE
how customize submit

### ISSUE THREAD

**Issue by shelbypo** [awsmin/wp-job-openings#46]
I have purchased the plugin for $199 . How modify the on submit button to close tab in browser Looking for the code

**Comment by aravindajith** [comment]
Unfortunately, modifying the on-submit button to close the browser tab is not a supported feature in the WP Job Openings plugin. Additionally, we cannot provide specific code for achieving this functionality.

Moreover, it's important to note that the success or error message after submitting an application is displayed only once the server response is received. If the tab were to close immediately upon clicking the submit button, the applicant would not be able to see the outcome of their submission, whether it was successful or encountered an error.

We recommend keeping the default behavior of the submit button intact to ensure applicants receive appropriate feedback regarding the status of their application. If you have any further questions or need assistance with other aspects of the plugin, please let us know.
